# Generated by Django 5.0.6 on 2024-06-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EasyTracker", "0006_wallet_created_at_wallet_user_alter_wallet_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="repeating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("none", "None"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
