# Generated by Django 5.0.6 on 2024-06-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EasyTracker", "0007_alter_transaction_repeating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("", "Transaction Type"),
                    ("income", "Income"),
                    ("expense", "Expense"),
                ],
                max_length=7,
            ),
        ),
    ]
