# Generated by Django 5.0.6 on 2024-06-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EasyTracker", "0009_alter_transaction_repeating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Category Name"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.FloatField(verbose_name="Amount"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="note",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Note"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="repeating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Repeating"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                ],
                max_length=20,
                null=True,
                verbose_name="Repeating",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("", "Transaction Type"),
                    ("income", "Income"),
                    ("expense", "Expense"),
                ],
                max_length=7,
                verbose_name="Type",
            ),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="exclude_from_total",
            field=models.BooleanField(verbose_name="Exclude from total"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="initial_balance",
            field=models.FloatField(default=0, verbose_name="Initial balance"),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Name"),
        ),
    ]
