# Generated by Django 5.0.6 on 2024-06-21 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EasyTracker", "0010_alter_category_name_alter_transaction_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="EasyTracker.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="wallet_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="EasyTracker.wallet",
                verbose_name="Wallet",
            ),
        ),
    ]
