# Generated by Django 5.0.6 on 2024-07-18 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EasyTracker", "0011_alter_transaction_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="expense",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="wallet",
            name="income",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
