# Generated by Django 5.0.6 on 2024-07-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EasyTracker", "0012_wallet_expense_wallet_income"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.PositiveIntegerField(verbose_name="Amount"),
        ),
    ]
