# Generated by Django 5.0.6 on 2024-07-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EasyTracker", "0013_alter_transaction_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.FloatField(verbose_name="Amount"),
        ),
    ]
