# Generated by Django 5.0.6 on 2024-09-21 17:29

import django.utils.timezone
import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("EasyTracker", "0015_wallet_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="jalali_date",
            field=django_jalali.db.models.jDateField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Jalali Date",
            ),
            preserve_default=False,
        ),
    ]
